### ISSUE TITLE
score-part shold be []

### ISSUE THREAD

**Issue by G10-blip** [IanWold/MusicXmlSharp#1]
Great Job! :-) and thanks for this.
I am not at all an expert, but it seems that "score-part" should be array-ed, because there can be more than one into one partlist.
I modified manually the scorepart.cs and now it works well even with more scoreparts into one partlist.

I won't dare to modify it in the repository ... ;-)

**Comment by IanWold** [comment]
Glad you're able to get some use from it :) Thanks for pointing this out. I do notice that the `partlist.Items` property does serialize "score-part"s. Reading the documentation provided by MusicXML for `part-list` (https://github.com/w3c/musicxml/blob/v3.1/schema/musicxml.xsd#L5536), it could be a quirk in the MusicXML definition that `partlist.scorepart` is only here to ensure there is at least one "score-part" in the "part-list". MusicXML's documentation is a bit difficult, but it could be the case that we're intended to access the score parts from the `partlist.Items` property. When you serialize a MusixXML document, are you able to see all the `scorepart`s in `partlist.Items` alright?

I'll try to do a bit more digging into this this weekend to see how this is resolved by other MusicXML libraries. It might actually be desirable to get rid of `partlist.partgroup` and `partlist.scorepart` and replace them with readonly properties returning the correctly-typed objects out of `partlist.Items` there?

**Comment by G10-blip** [comment]
Oppppsss...
You are fully right. :-)
Partlist.Items does serialize properly.

Please Forgive me.

I have made a bit of confusion.
Actually, reviewing scorepart arraying it, the matter works fine and
directly, but I prefer anyway to follow your logic and reviewed back
accordingly my code.

Sorry sorry for this... (I am still at the basics please forgive me, I will
try to learn faster.... Promise)

BTW i find your stuff great: direct for usage and pragmatic ;-).


Thanks again and have a great weekend
Cheers
Gio

**Comment by IanWold** [comment]
It's quite alright, no need to apologize :) This is a good comment - you raise a good point that the API from MusicXML is less than ideal, and a bit confusing here. Certainly, some work could be done in future to improve the library as a whole to make it friendlier for a .NET developer to consume. Disappointingly, I find MusicXML's documentation a bit unapproachable so it's tough to find all the situations where this code can be improved.

This weekend I did discover a couple other places where this same trick is used in the XSD, so I'll close this issue and later I'll open another issue to track those.
